apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        ports:
        - containerPort: 3130  # Change to match your app's port
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/myDatabase"  # Match this to your MongoDB deployment
        - name: SESSION_SECRET
          value: "1234"
        - name: EMAIL_USER
          value: "chagantyteja2502@gmail.com"
        - name: EMAIL_PASS
          value: "yxoq bjuk rdnt alzp"
        - name: PORT
          value: "3130"    
--- 
apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer is not supported
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    app: userprofile
